# CMake generated Testfile for 
# Source directory: /home/nathan/IsaacLab/.pinocchio-src/unittest/casadi
# Build directory: /home/nathan/IsaacLab/.pinocchio-build/unittest/casadi
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[pinocchio-test-cpp-casadi-basic]=] "/home/nathan/IsaacLab/.pinocchio-build/unittest/casadi/pinocchio-test-cpp-casadi-basic")
set_tests_properties([=[pinocchio-test-cpp-casadi-basic]=] PROPERTIES  DEPENDS "ctest_build_tests" TIMEOUT "3000" _BACKTRACE_TRIPLES "/home/nathan/IsaacLab/.pinocchio-build/_deps/jrl-cmakemodules-src/test.cmake;115;add_test;/home/nathan/IsaacLab/.pinocchio-src/unittest/CMakeLists.txt;57;add_unit_test;/home/nathan/IsaacLab/.pinocchio-src/unittest/casadi/CMakeLists.txt;6;add_pinocchio_unit_test;/home/nathan/IsaacLab/.pinocchio-src/unittest/casadi/CMakeLists.txt;16;add_casadi_unit_test;/home/nathan/IsaacLab/.pinocchio-src/unittest/casadi/CMakeLists.txt;0;")
add_test([=[pinocchio-test-cpp-casadi-spatial]=] "/home/nathan/IsaacLab/.pinocchio-build/unittest/casadi/pinocchio-test-cpp-casadi-spatial")
set_tests_properties([=[pinocchio-test-cpp-casadi-spatial]=] PROPERTIES  DEPENDS "ctest_build_tests" TIMEOUT "3000" _BACKTRACE_TRIPLES "/home/nathan/IsaacLab/.pinocchio-build/_deps/jrl-cmakemodules-src/test.cmake;115;add_test;/home/nathan/IsaacLab/.pinocchio-src/unittest/CMakeLists.txt;57;add_unit_test;/home/nathan/IsaacLab/.pinocchio-src/unittest/casadi/CMakeLists.txt;6;add_pinocchio_unit_test;/home/nathan/IsaacLab/.pinocchio-src/unittest/casadi/CMakeLists.txt;17;add_casadi_unit_test;/home/nathan/IsaacLab/.pinocchio-src/unittest/casadi/CMakeLists.txt;0;")
add_test([=[pinocchio-test-cpp-casadi-explog]=] "/home/nathan/IsaacLab/.pinocchio-build/unittest/casadi/pinocchio-test-cpp-casadi-explog")
set_tests_properties([=[pinocchio-test-cpp-casadi-explog]=] PROPERTIES  DEPENDS "ctest_build_tests" TIMEOUT "3000" _BACKTRACE_TRIPLES "/home/nathan/IsaacLab/.pinocchio-build/_deps/jrl-cmakemodules-src/test.cmake;115;add_test;/home/nathan/IsaacLab/.pinocchio-src/unittest/CMakeLists.txt;57;add_unit_test;/home/nathan/IsaacLab/.pinocchio-src/unittest/casadi/CMakeLists.txt;6;add_pinocchio_unit_test;/home/nathan/IsaacLab/.pinocchio-src/unittest/casadi/CMakeLists.txt;18;add_casadi_unit_test;/home/nathan/IsaacLab/.pinocchio-src/unittest/casadi/CMakeLists.txt;0;")
add_test([=[pinocchio-test-cpp-casadi-joints]=] "/home/nathan/IsaacLab/.pinocchio-build/unittest/casadi/pinocchio-test-cpp-casadi-joints")
set_tests_properties([=[pinocchio-test-cpp-casadi-joints]=] PROPERTIES  DEPENDS "ctest_build_tests" TIMEOUT "3000" _BACKTRACE_TRIPLES "/home/nathan/IsaacLab/.pinocchio-build/_deps/jrl-cmakemodules-src/test.cmake;115;add_test;/home/nathan/IsaacLab/.pinocchio-src/unittest/CMakeLists.txt;57;add_unit_test;/home/nathan/IsaacLab/.pinocchio-src/unittest/casadi/CMakeLists.txt;6;add_pinocchio_unit_test;/home/nathan/IsaacLab/.pinocchio-src/unittest/casadi/CMakeLists.txt;19;add_casadi_unit_test;/home/nathan/IsaacLab/.pinocchio-src/unittest/casadi/CMakeLists.txt;0;")
add_test([=[pinocchio-test-cpp-casadi-algorithms]=] "/home/nathan/IsaacLab/.pinocchio-build/unittest/casadi/pinocchio-test-cpp-casadi-algorithms")
set_tests_properties([=[pinocchio-test-cpp-casadi-algorithms]=] PROPERTIES  DEPENDS "ctest_build_tests" TIMEOUT "3000" _BACKTRACE_TRIPLES "/home/nathan/IsaacLab/.pinocchio-build/_deps/jrl-cmakemodules-src/test.cmake;115;add_test;/home/nathan/IsaacLab/.pinocchio-src/unittest/CMakeLists.txt;57;add_unit_test;/home/nathan/IsaacLab/.pinocchio-src/unittest/casadi/CMakeLists.txt;6;add_pinocchio_unit_test;/home/nathan/IsaacLab/.pinocchio-src/unittest/casadi/CMakeLists.txt;20;add_casadi_unit_test;/home/nathan/IsaacLab/.pinocchio-src/unittest/casadi/CMakeLists.txt;0;")
add_test([=[pinocchio-test-cpp-casadi-integrate-derivatives]=] "/home/nathan/IsaacLab/.pinocchio-build/unittest/casadi/pinocchio-test-cpp-casadi-integrate-derivatives")
set_tests_properties([=[pinocchio-test-cpp-casadi-integrate-derivatives]=] PROPERTIES  DEPENDS "ctest_build_tests" TIMEOUT "3000" _BACKTRACE_TRIPLES "/home/nathan/IsaacLab/.pinocchio-build/_deps/jrl-cmakemodules-src/test.cmake;115;add_test;/home/nathan/IsaacLab/.pinocchio-src/unittest/CMakeLists.txt;57;add_unit_test;/home/nathan/IsaacLab/.pinocchio-src/unittest/casadi/CMakeLists.txt;6;add_pinocchio_unit_test;/home/nathan/IsaacLab/.pinocchio-src/unittest/casadi/CMakeLists.txt;27;add_casadi_unit_test;/home/nathan/IsaacLab/.pinocchio-src/unittest/casadi/CMakeLists.txt;0;")
add_test([=[pinocchio-test-cpp-casadi-rnea-derivatives]=] "/home/nathan/IsaacLab/.pinocchio-build/unittest/casadi/pinocchio-test-cpp-casadi-rnea-derivatives")
set_tests_properties([=[pinocchio-test-cpp-casadi-rnea-derivatives]=] PROPERTIES  DEPENDS "ctest_build_tests" TIMEOUT "3000" _BACKTRACE_TRIPLES "/home/nathan/IsaacLab/.pinocchio-build/_deps/jrl-cmakemodules-src/test.cmake;115;add_test;/home/nathan/IsaacLab/.pinocchio-src/unittest/CMakeLists.txt;57;add_unit_test;/home/nathan/IsaacLab/.pinocchio-src/unittest/casadi/CMakeLists.txt;6;add_pinocchio_unit_test;/home/nathan/IsaacLab/.pinocchio-src/unittest/casadi/CMakeLists.txt;28;add_casadi_unit_test;/home/nathan/IsaacLab/.pinocchio-src/unittest/casadi/CMakeLists.txt;0;")
